### ISSUE TITLE
Small issue - show global variables  / status

### ISSUE THREAD

**Issue by freddielunchbird** [Tusamarco/proxy_sql_tools#1]
Hi,
you have made a nice script but when i glanced over it I found:

    sub new {
        my $class = shift;
        my $SQL_get_variables="SHOW GLOBAL VARIABLES LIKE 'wsrep%";
        my $SQL_get_status="SHOW GLOBAL VARIABLES LIKE 'wsrep%";
        my $SQL_get_read_only="SHOW GLOBAL VARIABLES LIKE 'read_only'";  

and i believe you should change:

        my $SQL_get_status="SHOW GLOBAL VARIABLES LIKE 'wsrep%";
to

        my $SQL_get_status="SHOW GLOBAL STATUS LIKE 'wsrep%";

Thanks!

Johan Andersson :)

**Comment by Tusamarco** [comment]
Tks Johan, actually that was not used yet this is why I did not noticed ;) and why is not affecting the work.
WIll fix it.

**Comment by Tusamarco** [comment]
fixed
