### ISSUE TITLE
The intro post lacks READ/WRITE splitting between groups 500, 501.

### ISSUE THREAD

**Issue by ethaniel** [Tusamarco/proxy_sql_tools#4]
I've thoroughly read the post about ProxySQL and Percona XtraDB Cluster (Galera) Integration (https://www.percona.com/blog/2016/09/15/proxysql-percona-cluster-galera-integration/) but I can't figure out how ProxySQL handles READ/WRITE splitting between Hostgroups 500, 501 in multiwriter mode when the mysql_replication_hostgroups table is empty.

The post tells us to do "delete from mysql_servers where hostgroup_id in (500,501);" but there is no replacement.

I've found that the HA post has more info on this. But most users will not read it, and read intro instead. I think it's worth adding the mysql_users and mysql_query_rules parts in there too.

Also, that same block has a code error:
```
LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL TO DISK;
```
it needs to be:
```
LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;
```

Thank you for the amazing intro!

**Comment by Tusamarco** [comment]
I do not understand the _The post tells us to do "delete from mysql_servers where hostgroup_id in (500,501);" but there is no replacement._
after the delete command we have all the inserts needed to refill the table.
