### ISSUE TITLE
The HA post has a code error

### ISSUE THREAD

**Issue by ethaniel** [Tusamarco/proxy_sql_tools#5]
Post: https://www.percona.com/blog/2017/01/19/setup-proxysql-for-high-availability-not-single-point-failure/

SELECT FOR UPDATE should be sent to the WRITE servers (group 500). Am I wrong?

I assume:
```
INSERT INTO mysql_query_rules (rule_id,username,destination_hostgroup,active,retries,match_digest,apply) VALUES(200,'load_RW',501,1,3,'^SELECT.*FOR UPDATE',1);
```

probably should be

```
INSERT INTO mysql_query_rules (rule_id,username,destination_hostgroup,active,retries,match_digest,apply) VALUES(200,'load_RW',500,1,3,'^SELECT.*FOR UPDATE',1);
```

**Comment by Tusamarco** [comment]
U are right is a typo for cut-paste I cannot change it will ask the
editor to do it.


------------------------------------------------
Marco Tusa, 
Mobile: +1-613-282-7337
do something for your planet!
http://www.tusacentral.net/
------------------------------------------------
Save a tree... please don't print this e-mail unless you really need to

**Comment by Tusamarco** [comment]
done fixed
