### ISSUE TITLE
Error in documentation.

### ISSUE THREAD

**Issue by ethaniel** [Tusamarco/proxy_sql_tools#7]
`This check does NOT modify any state of the Nodes. Meaning It will NOT modify any variables or settings in the original node. It will ONLY change states in ProxySQL.
`

But your script does edit the READ_ONLY variable on the node. So this contradicts the documentation.

**Comment by Tusamarco** [comment]
No as I said clear the feature that modify the READ_ONLY is
experimental, and once more not to be used.

For that part I am working to a script that is actually acting in
parallel  with this but that does better check and election.
That feature is NOT meant to be use in production ever, given has no lock
and multiple ProxySQL could act at the same time.


------------------------------------------------
Marco Tusa, 
Mobile: +1-613-282-7337
do something for your planet!
http://www.tusacentral.net/
------------------------------------------------
Save a tree... please don't print this e-mail unless you really need to
